name: R-CI

on:
  push:
  pull_request:

jobs:
  R-CI:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - uses: actions/checkout@v3

      - name: Check package
        run: |
          sudo dnf --assumeyes install git
          git clone https://github.com/stewid/ansible-r-ci.git
          curl -OLs https://stewid.github.io/ansible-r-ci/r-ci.yml
          ansible-playbook -i localhost, r-ci.yml
